#ifndef CA_FUNCTIONIDS_H
#define CA_FUNCTIONIDS_H

//
// ca_utility.c
//

#define CA_FID_RESET 0x00
#define CA_FID_GETHARDWAREVERSION 0x01
#define CA_FID_GETFIRMWAREVERSION 0x02

#define CA_FID_ERASEUSERDATASECTOR 0x04
#define CA_FID_WRITEUSERDATA 0x05
#define CA_FID_READUSERDATA 0x06

#define CA_FID_SETMODE 0x07

#define CA_FID_GETHSTG 0x08
#define CA_FID_SETHSTG 0x09

#define CA_FID_GETDATETIME 0x0A
#define CA_FID_SETDATETIME 0x0B

#define CA_FID_GETSLAVEADDRESS 0x0A
#define CA_FID_SETSLAVEADDRESS 0x0B
#define CA_FID_GETSLAVEACTIVE 0x0C

#define CA_FID_SETWATCHDOG 0x0D

//
// ca_analog.c
//

#define CA_FID_GETSENSORBOXA 0x10
#define CA_FID_GETSENSORBOXA2 0x7E

#define CA_FID_GETSENSORBOXB 0x11
#define CA_FID_GETSENSORBOXB2 0x7F

#define CA_FID_GETCONTROLMODE 0x10
#define CA_FID_GETMEASUREMENTMODE 0x11

#define CA_FID_GETINPUTVALUEA 0x12
#define CA_FID_GETINPUTVALUEB 0x13

#define CA_FID_GETVALUEUI 0x12
#define CA_FID_GETVALUEIU 0x13

#define CA_FID_GETVALUEA 0x12
#define CA_FID_GETVALUEB 0x13
#define CA_FID_GETVALUEX 0x62
#define CA_FID_GETVALUEY 0x63

#define CA_FID_GETMMMSINPUTVALUEA 0x16
#define CA_FID_GETMMMSINPUTVALUEB 0x17
#define CA_FID_GETMMMSVALUEUI 0x16
#define CA_FID_GETMMMSVALUEIU 0x17

#define CA_FID_GETMMMSVALUEA 0x16
#define CA_FID_GETMMMSVALUEB 0x17
#define CA_FID_GETMMMSVALUEX 0x66
#define CA_FID_GETMMMSVALUEY 0x67

#define CA_FID_GETCOSINPUTVALUEAB 0x18
#define CA_FID_GETCOSVALUEUI 0x18
#define CA_FID_GETCOSVALUEIU 0x18

#define CA_FID_GETCOSVALUEAB 0x18
#define CA_FID_GETCOSVALUEXA 0x68

#define CA_FID_SENDSERIALSENSORDATAA 0x2D
#define CA_FID_SENDSERIALSENSORDATAB 0x2E

#define CA_FID_SETMEANTIME 0x2F

//
// ca_relay.c
//

#define CA_FID_SETRELAYVOLTAGE 0x19
#define CA_FID_SETRELAY 0x2B
#define CA_FID_SETVOLTAGE 0x2C

//
// ca_digital.c
//

#define CA_FID_GETBITINPUT 0x50
#define CA_FID_SETBITOUTPUT 0x51

#define CA_FID_GETDIGITALINPUTS 0x52
#define CA_FID_SETDIGITALOUTPUTS 0x53

#define CA_FID_SETCOUNTERMODE 0x54
#define CA_FID_SETCOUNTERDELAY 0x55

#define CA_FID_GETCOUNTER 0x56
#define CA_FID_SETCOUNTER 0x57

#define CA_FID_SETREFERENCEPOINT 0x58
#define CA_FID_SETSTEPPERDELAY 0x59

#define CA_FID_GETPHYSICALPOSITION 0x5A
#define CA_FID_GETLOGICALPOSITION 0x5B

#define CA_FID_MOVETOABSPOSITION 0x5C
#define CA_FID_MOVETORELPOSITION 0x5D

//
// ca_oscilloscope.c
//

#define CA_FID_RESETOSCILLOSCOPE 0x1A
#define CA_FID_RESETOSCILLOSCOPE2 0x70

#define CA_FID_STARTOSCILLOSCOPE 0x1B
#define CA_FID_STOPOSCILLOSCOPE 0x1C

#define CA_FID_GETOSCILLOSCOPESTATUS 0x1D
#define CA_FID_GETOSCILLOSCOPESTATUS2 0x71

#define CA_FID_GETOSCILLOSCOPETIME 0x74
#define CA_FID_GETOSCILLOSCOPETIME2 0x75

#define CA_FID_GETOSCILLOSCOPEARRAYA 0x1E
#define CA_FID_GETOSCILLOSCOPEARRAYB 0x1F
#define CA_FID_GETOSCILLOSCOPEARRAYX 0x6E
#define CA_FID_GETOSCILLOSCOPEARRAYY 0x6F

#define CA_FID_GETOSCILLOSCOPEARRAY2A 0x72
#define CA_FID_GETOSCILLOSCOPEARRAY2B 0x73

#endif
