#ifndef CA_FUNCTIONIDS_HEADER
#define CA_FUNCTIONIDS_HEADER

#define FID_RESET 0x00
#define FID_GETHARDWAREVERSION 0x01
#define FID_GETFIRMWAREVERSION 0x02

#define FID_ERASEUSERDATASECTOR 0x04
#define FID_WRITEUSERDATA 0x05
#define FID_READUSERDATA 0x06

#define FID_SETMODE 0x07

#define FID_GETHSTG 0x08
#define FID_SETHSTG 0x09

#define FID_GETDATETIME 0x0A
#define FID_SETDATETIME 0x0B

#define FID_READDATALOGGER 0x0C

#define FID_GETSLAVEADDRESS 0x0A
#define FID_SETSLAVEADDRESS 0x0B
#define FID_GETSLAVEACTIVE 0x0C

#define FID_SETWATCHDOG 0x0D

#define FID_GETSENSORBOXA 0x10
#define FID_GETSENSORBOXA2 0x7E

#define FID_GETSENSORBOXB 0x11
#define FID_GETSENSORBOXB2 0x7F

#define FID_GETCONTROLMODE 0x10
#define FID_GETMEASUREMENTMODE 0x11

#define FID_GETINPUTVALUEA 0x12
#define FID_GETINPUTVALUEB 0x13

#define FID_GETVALUEUI 0x12
#define FID_GETVALUEIU 0x13

#define FID_GETVALUEA 0x12
#define FID_GETVALUEB 0x13
#define FID_GETVALUEX 0x62
#define FID_GETVALUEY 0x63

// TODO: special sensor boxes

#define FID_GETMMMSINPUTVALUEA 0x16
#define FID_GETMMMSINPUTVALUEB 0x17
#define FID_GETMMMSVALUEUI 0x16
#define FID_GETMMMSVALUEIU 0x17

#define FID_GETMMMSVALUEA 0x16
#define FID_GETMMMSVALUEB 0x17
#define FID_GETMMMSVALUEX 0x66

#define FID_GETCOSINPUTVALUEAB 0x18
#define FID_GETCOSVALUEUI 0x18
#define FID_GETCOSVALUEIU 0x18

#define FID_GETCOSVALUEAB 0x18
#define FID_GETCOSVALUEXA 0x68

#define FID_SENDSERIALSENSORDATAA 0x2D
#define FID_SENDSERIALSENSORDATAB 0x2E

#define FID_SETMEANTIME 0x2F

#define FID_SETRELAYVOLTAGE 0x19
#define FID_SETRELAY 0x2B
#define FID_SETVOLTAGE 0x2C

#define FID_GETBITINPUT 0x50
#define FID_SETBITOUTPUT 0x51

#define FID_GETDIGITALINPUTS 0x52
#define FID_SETDIGITALOUTPUTS 0x53

#define FID_SETCOUNTERMODE 0x54
#define FID_SETCOUNTERDELAY 0x55

#define FID_GETCOUNTER 0x56
#define FID_SETCOUNTER 0x57

#define FID_SETREFERENCEPOINT 0x58
#define FID_SETSTEPPERDELAY 0x59

#define FID_GETPHYSICALPOSITION 0x5A
#define FID_GETLOGICALPOSITION 0x5B

#define FID_MOVETOABSPOSITION 0x5C
#define FID_MOVETORELPOSITION 0x5D

#define FID_RESETOSCILLOSCOPE 0x1A
#define FID_RESETOSCILLOSCOPE2 0x70

#define FID_STARTOSCILLOSCOPE 0x1B
#define FID_STOPOSCILLOSCOPE 0x1C

#define FID_GETOSCILLOSCOPESTATUS 0x1D
#define FID_GETOSCILLOSCOPESTATUS2 0x71

#define FID_GETOSCILLOSCOPETIME 0x74
#define FID_GETOSCILLOSCOPETIME2 0x75

#define FID_GETOSCILLOSCOPEARRAYA 0x1E
#define FID_GETOSCILLOSCOPEARRAYB 0x1F
#define FID_GETOSCILLOSCOPEARRAYX 0x6E
#define FID_GETOSCILLOSCOPEARRAYY 0x6F

#define FID_GETOSCILLOSCOPEARRAY2A 0x72
#define FID_GETOSCILLOSCOPEARRAY2B 0x73

// TODO: lots of other ids

#endif
